version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # 自动建表

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  backend:
    image: crpi-qbqc3mvo2gxrnwcm.cn-beijing.personal.cr.aliyuncs.com/habitbuilder/habitbuilder-back:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: redis

  frontend:
    image: crpi-qbqc3mvo2gxrnwcm.cn-beijing.personal.cr.aliyuncs.com/habitbuilder/habitbuilder-front:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
